name: ESLint
on:
  pull_request:
    branches:
      - main
jobs:
  Lint-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        run: npm ci # OR: yarn
      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v5.2
      
